"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import styles from "./admin.module.css";

type Payment = { razorpay_order_id:string; razorpay_payment_id?:string; amount:number; currency:string; status:string };
type Participant = { name?:string; email?:string; college?:string };
type Registration = { id:string; registrationCode:string; eventSlug:string; name:string; email:string; phone:string; college:string; year:string; branch:string; teamName?:string; teamSize:number; participants:Participant[]; status:string; createdAt:string; payment:Payment|null };
const EVENT_NAMES:Record<string,string>={"infinity-trials":"Infinity Trials","research-x":"Research X","bgmi-elite-showdown":"BGMI Elite Showdown","tech-roulette":"Tech Roulette",storyverse:"StoryVerse"};

export default function AdminPage(){
 const [session,setSession]=useState<string|null>(null),[email,setEmail]=useState("chinmay.joshi25@pccoepune.org"),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[rows,setRows]=useState<Registration[]>([]),[event,setEvent]=useState("all"),[query,setQuery]=useState(""),[synced,setSynced]=useState("");
 useEffect(()=>{const auth=supabaseBrowser().auth;auth.getSession().then(({data})=>{setSession(data.session?.access_token||null);setLoading(false)});const{data}=auth.onAuthStateChange((_e,s)=>setSession(s?.access_token||null));return()=>data.subscription.unsubscribe()},[]);
 const load=useCallback(async(token:string)=>{try{const response=await fetch("/api/admin/registrations",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load dashboard");setRows(body.registrations);setSynced(body.syncedAt);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard")}},[]);
 useEffect(()=>{if(!session)return;load(session);const timer=setInterval(()=>load(session),8000);return()=>clearInterval(timer)},[session,load]);
 async function login(e:FormEvent){e.preventDefault();setLoading(true);setError("");const{data,error}=await supabaseBrowser().auth.signInWithPassword({email:email.trim(),password});if(error)setError(error.message);else setSession(data.session?.access_token||null);setLoading(false)}
 const filtered=useMemo(()=>rows.filter(r=>(event==="all"||r.eventSlug===event)&&(!query||[r.registrationCode,r.name,r.email,r.phone,r.teamName,r.college].some(v=>v?.toLowerCase().includes(query.toLowerCase())))),[rows,event,query]);
 function downloadExcel(){
  const quote=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
  const header=["Registration Code","Status","Event","Team Name","Leader Name","Leader Email","Phone","College","Year","Branch","Team Size","Participants","Payment Status","Amount (INR)","Razorpay Order ID","Razorpay Payment ID","Registered At"];
  const lines=filtered.map(r=>[r.registrationCode,r.status,EVENT_NAMES[r.eventSlug]||r.eventSlug,r.teamName||"",r.name,r.email,r.phone,r.college,r.year,r.branch,r.teamSize||1,(r.participants||[]).map(p=>`${p.name||"Member"} <${p.email||""}>${p.college?` — ${p.college}`:""}`).join(" | "),r.payment?.status||"no payment",r.payment?.amount||0,r.payment?.razorpay_order_id||"",r.payment?.razorpay_payment_id||"",new Date(r.createdAt).toLocaleString("en-IN")].map(quote).join(","));
  const blob=new Blob(["\uFEFF",header.map(quote).join(","),"\r\n",lines.join("\r\n")],{type:"text/csv;charset=utf-8"});
  const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`praxis-registrations-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);
 }
 const confirmed=rows.filter(r=>r.status==="confirmed").length,paid=rows.filter(r=>r.payment?.status==="paid").reduce((n,r)=>n+Number(r.payment?.amount||0),0),people=rows.reduce((n,r)=>n+(r.teamSize||1),0);
 if(loading&&!session)return <main className={styles.shell}><div className={styles.loader}>CONNECTING TO PRAXIS CORE…</div></main>;
 if(!session)return <main className={styles.shell}><section className={styles.login}><img src="/images/praxis_new_logo.png" alt="Praxis 2026"/><span>SECURE OPERATIONS CONSOLE</span><h1>Admin access</h1><p>Sign in to view live Supabase registration data.</p><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password" autoFocus/></label>{error&&<p className={styles.error}>{error}</p>}<button disabled={loading}>{loading?"AUTHENTICATING…":"ENTER DASHBOARD"}</button></form></section></main>;
 return <main className={styles.dashboard}><header><div><img src="/images/praxis_new_logo.png" alt="Praxis 2026"/><span>REGISTRATION COMMAND</span></div><button onClick={()=>supabaseBrowser().auth.signOut()}>Sign out</button></header><section className={styles.hero}><div><span>LIVE SUPABASE FEED</span><h1>Event registrations</h1><p>{synced?`Last synced ${new Date(synced).toLocaleTimeString()}`:"Synchronizing…"} · refreshes every 8 seconds</p></div><div className={styles.heroActions}><button onClick={downloadExcel} disabled={!filtered.length}>Download Excel ↓</button><button onClick={()=>session&&load(session)}>Refresh now ↻</button></div></section>{error&&<p className={styles.error}>{error}</p>}<section className={styles.stats}><article><span>TOTAL REGISTRATIONS</span><strong>{rows.length}</strong></article><article><span>CONFIRMED</span><strong>{confirmed}</strong></article><article><span>PARTICIPANTS</span><strong>{people}</strong></article><article><span>PAYMENTS CAPTURED</span><strong>₹{paid.toLocaleString("en-IN")}</strong></article></section><section className={styles.controls}><input type="search" placeholder="Search name, email, phone, team or code" value={query} onChange={e=>setQuery(e.target.value)}/><select value={event} onChange={e=>setEvent(e.target.value)}><option value="all">All events</option>{Object.entries(EVENT_NAMES).map(([slug,name])=><option key={slug} value={slug}>{name}</option>)}</select><span>{filtered.length} records</span></section><section className={styles.tableWrap}><table><thead><tr><th>Registration</th><th>Event</th><th>Leader / Team</th><th>Contact</th><th>Members</th><th>Payment</th><th>Created</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.registrationCode}</b><em className={r.status==="confirmed"?styles.good:styles.pending}>{r.status}</em></td><td>{EVENT_NAMES[r.eventSlug]||r.eventSlug}</td><td><b>{r.teamName||r.name}</b><small>{r.teamName&&`Leader: ${r.name}`}</small><small>{r.college}</small></td><td><a href={`mailto:${r.email}`}>{r.email}</a><small>{r.phone}</small></td><td><b>{r.teamSize||1}</b>{r.participants?.map((p,i)=><small key={i}>{p.name||"Member"} · {p.email}</small>)}</td><td><b>{r.payment?`₹${Number(r.payment.amount).toLocaleString("en-IN")}`:"Free / none"}</b><em className={r.payment?.status==="paid"?styles.good:styles.pending}>{r.payment?.status||"no payment"}</em>{r.payment?.razorpay_payment_id&&<small>{r.payment.razorpay_payment_id}</small>}</td><td>{new Date(r.createdAt).toLocaleDateString("en-IN")}<small>{new Date(r.createdAt).toLocaleTimeString("en-IN")}</small></td></tr>)}</tbody></table>{!filtered.length&&<div className={styles.empty}>No registrations match this view.</div>}</section></main>;
}
