// Web-sized copies of the supplied p25 folder. Original photos are preserved.
export const GALLERY = [
  { id: "praxis-02", title: "All the energy. One frame.", category: "The collective", alt: "A large group posing in front of a Praxis display in a room with red lighting", description: "The people, the preparation, and the energy that bring Praxis to life.", fit: "contain", position: "center" },
  { id: "praxis-04", title: "Inside the arena.", category: "In the arena", alt: "Participants working at computer stations in a room illuminated with purple and red lights", description: "Screens on. Ideas in motion. A glimpse inside the event floor.", fit: "contain", position: "center" },
  { id: "praxis-10", title: "A moment together.", category: "The collective", alt: "Students and guests gathered for a group photograph at the front of a classroom", description: "A shared frame for the people who made the experience possible.", fit: "contain", position: "center" },
  { id: "praxis-01", title: "The faces of Praxis.", category: "The collective", alt: "A group of students wearing dark blue shirts posing together in a classroom", description: "Different strengths, familiar faces, and a whole lot of team spirit.", fit: "contain", position: "center" },
  { id: "praxis-03", title: "Focus, captured.", category: "In the arena", alt: "Participants focused on computer screens in a dimly lit event room", description: "Those quieter moments when all attention turns to the challenge.", fit: "contain", position: "center" },
  { id: "praxis-07", title: "Made with team spirit.", category: "The collective", alt: "Four students posing beside a handmade Praxis display", description: "The little details and shared efforts behind a bigger experience.", fit: "contain", position: "center" },
  { id: "praxis-08", title: "An audience of possibilities.", category: "On stage", alt: "An audience seated in a classroom watching a speaker at a lectern", description: "Coming together to listen, learn, and be part of the moment.", fit: "contain", position: "center" },
  { id: "praxis-09", title: "Ready for the day.", category: "The collective", alt: "Four students in dark shirts standing together beside a decorated table", description: "The people behind the preparations, ready to make it happen.", fit: "contain", position: "center" },
  { id: "praxis-05", title: "Ideas in action.", category: "In the arena", alt: "Participants working together at computer stations in a bright event room", description: "Collaboration, concentration, and challenges unfolding across the room.", fit: "contain", position: "center" },
  { id: "praxis-06", title: "Together beyond the arena.", category: "The collective", alt: "Praxis team members posing together outside the venue", description: "The team spirit that continues beyond the event floor.", fit: "contain", position: "center" },
  { id: "praxis-11", title: "A warm Praxis welcome.", category: "Guest address", alt: "A faculty member presenting flowers to the Praxis guest speaker", description: "Welcoming our guest with gratitude before an inspiring address.", fit: "contain", position: "center" },
  { id: "praxis-12", title: "One team. One Praxis.", category: "The collective", alt: "The Praxis team and faculty posing together outside the venue", description: "The complete team, together in one frame after making the experience possible.", fit: "contain", position: "center" },
  { id: "praxis-13", title: "The room that brought us together.", category: "The collective", alt: "A full classroom of attendees gathered for a group photograph", description: "One final wide view of the faces and connections behind the experience.", fit: "contain", position: "center" },
] as const;
